### ISSUE TITLE
Move splitpoints to frame boundaries

### ISSUE THREAD

**Issue by mp3splt** [mp3splt/mp3splt#76]
Imported from SourceForge on 2020-09-13 14:32:56
Created by **[*anonymous](https://sourceforge.net/u/*anonymous/)** on 2010-02-10 20:13:48
Original: https://sourceforge.net/p/mp3splt/feature-requests/65

---

It would be great to have an option to auto-move splitpoints to force them to be on frame boundaries. This would be very useful when splitting mix albums + cuefiles, allowing them to be played back (using a player capable of gapless output) without audio glitches.

related info here:
http://www.rockbox.org/wiki/GeneralFAQ#Does_Rockbox_support_gapless_pla
http://www.hydrogenaudio.org/forums/index.php?showtopic=15177&st=50&p=202024&#entry202024

**Comment by mp3splt** [comment]
Imported from SourceForge on 2020-09-13 14:32:57
Created by **[io_alex_2004](https://sourceforge.net/u/io_alex_2004/)** on 2015-03-04 00:10:23
Original: https://sourceforge.net/p/mp3splt/feature-requests/65/#db1d

---

An experimental option has been added to latest version (2.6.2 & 0.9.2 for the GUI).

-- 
Alex

**Comment by mp3splt** [comment]
Imported from SourceForge on 2020-09-13 14:33:00
Created by **[io_alex_2004](https://sourceforge.net/u/io_alex_2004/)** on 2015-03-04 00:10:40
Original: https://sourceforge.net/p/mp3splt/feature-requests/65/#3a7d

---

- **status**: open --> closed
- **Group**:  --> Next_Release_(example)

**Comment by msdobrescu** [comment]
Hi, I second the original poster. My question is, how could ensure splitting by the cue file frames number exactly for mp3 files?
I mean, how to control the frames number to cut, not to guess around a specified time?
I would take the cue file index and convert it to the number of frames (mm:ss:ff --> mm*4500 + ss*75 + ff), and split using that.
Is that possible already?
